version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: $MYSQL_CONTAINER_NAME
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
