version: '3'

services:
  postgres:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volume/pg:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
    restart: always

  pgadmin:
    image: dpage/pgadmin4:6.13
    environment:
      PGADMIN_DEFAULT_EMAIL: "robertomdiniz@protonmail.com"
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network
    restart: always

networks:
  postgres-compose-network:
    driver: bridge


